### ISSUE TITLE
dotimes - wrong count of do's

### ISSUE THREAD

**Issue by furesoft** [rzubek/CSLisp#11]
when im using the dotimes makro say for (x 10) it does it 11 times. So the semantic is not clear, because when you count up from 0 10 times it should end with 9
0 1 2 3 4 5 6 7 8 9 -> 10 times
0 1 2 3 4 5 6 7 8 9 10 -> 11 times

**Comment by rzubek** [comment]
Can you give me a repro case? 

(dotimes (i 3) ...) does produce 3 values, and those values are 0, 1 and 2.

For example see this unit test:
```csharp
  CompileAndRun(ctx, "(let ((r '())) (dotimes (i 3) (set! r (cons i r))) r)", "(2 1 0)");
```
Is this not what you're seeing?

**Comment by furesoft** [comment]
` (dotimes (x 10) (trace x))`

**Comment by rzubek** [comment]
The dotimes macro only executes 10 times. 

What you're seeing is the REPL displaying the final value of x, after it's returned from the dotimes. 

Do this to ignore the return value and return a different one:

```lisp
> (begin (dotimes (x 3) (trace x)) 'foo)
0
1
2
core:foo
```
