### ISSUE TITLE
make-struct Command

### ISSUE THREAD

**Issue by furesoft** [rzubek/CSLisp#3]
(make-struct point '(x y)) ->
      (make-point 1 3)
      (point? instance)
and getter/setter for the properties

maybe add interfaces too that can be implemented

**Comment by rzubek** [comment]
Please let me know what you have in mind in terms of implementation!

**Comment by furesoft** [comment]
we create a struct in c# with a Symbol for the name of the struct and the struct inherits from a list
make-struct creates an instance of this struct and generates the neccessary procedures (constructor, predicate, getter, setter)

**Comment by rzubek** [comment]
So it sounds like the first step would be adding a new internal list of values.

Say a `public class Vector : List<Val> { }` that is going to serve as a list of engine-side values (let's call it a vector for compatibility with other lisps for example) - plus appropriate accessors like
```lisp
(make-vector len name)
(get-vector-length v)
(get-vector-element v n)
(set-vector-element! v n val)
```

And then after that, your proposed `make-struct` would be a macro that defines the appropriate `make-point`, `get-point-x`, `point?` and other functions in terms of vector calls. Does that sound right?

**Comment by furesoft** [comment]
that sounds great, but i have no knowlege about defining macros in lisp

**Comment by furesoft** [comment]
and make a overload for (make-vector '(1 2 3))
to initialize the vector

**Comment by rzubek** [comment]
Ah, in this case would you like to take a stab at the various `vector` functions? Those would be just regular primitive operators in C#. And then we can worry about the macros later.

**Comment by furesoft** [comment]
but it makes no sense to store a name in the vector, when we call make-struct we could generate a touple wiht(symbol, vector) and for accessing items use the second and for instance check use the first

**Comment by rzubek** [comment]
You mean a list or a dotted pair? Or a separate data structure on the CLR side?

**Comment by furesoft** [comment]
dotted pair

**Comment by rzubek** [comment]
I don't think the vector itself should be a special dotted pair with a List in the cdr - it should be just the bare List itself.

So let's just not put the name in the vector - it's not needed for the vector implementation, only for structs, and those can handle the name instead.

**Comment by furesoft** [comment]
what is the current state of make-struct macro?

**Comment by rzubek** [comment]
Oh yeah, I took a stab at it. Check out `record.lisp`

```lisp

;;
;; Usage examples:

; (define-record-type point 
;   	(make-point x y) 
;   	point? 
;   	(x getx setx!) 
;   	(y gety))

; (set! p (make-point 1 2)) ; => point object
;
; (point? p)      ; => #t
; (point? '(a b)) ; => #f
;
; (getx p)     ; => 1
; (gety p)     ; => 2
;
; (setx! p 42) ; => 42
; (getx p)     ; => 42
;
; ; (sety! p 42) ; => error, this accessor is not defined

```

Currently in beta, it's working but needs unit tests etc.

**Comment by rzubek** [comment]
Also I tweaked the vector api, so now it's `vector-get`, `vector-set!` etc

**Comment by rzubek** [comment]
Documentation updated in https://github.com/rzubek/CSLisp/commit/94dd58041f879ef4f838c6b8e831b419cdfdb773
