### ISSUE TITLE
Implement core library

### ISSUE THREAD

**Issue by furesoft** [rzubek/CSLisp#5]
Math Functions
Tree Functions
Network
IO
Data (JSON, XML, S-Expressions)
...

**Comment by rzubek** [comment]
Agreed! Let me get a little further on CLR interop and we should be able to define a good chunk of those as shortcuts to .NET standard libraries.

**Comment by rzubek** [comment]
Moved to this discussion thread:
[Discussion about Core libraries](https://github.com/rzubek/CSLisp/discussions/10)
