### ISSUE TITLE
add chaining procedures

### ISSUE THREAD

**Issue by furesoft** [rzubek/CSLisp#6]
add the ability to chain procedures

(define myfunc (chain func1 func 2 func3))

(myfunc 123)

that approach is good for building parsers

may we could write a parser combinator library

**Comment by furesoft** [comment]
that could be implemented as macro -

**Comment by rzubek** [comment]
Now that both eval and apply exist, would you like to take a stab at it?

**Comment by furesoft** [comment]
looks great

**Comment by furesoft** [comment]
but it does not work as expected, we need a chain function

we need a macro that turns this:

`(chain first second third)`

`
(lambda (x) (
(third (second (first x))) 
))`

**Comment by rzubek** [comment]
That's right, that would be perfect for a macro.
If you'd like to give it a try, it might be an interesting challenge!
Otherwise I'll take a stab at it next time I'm in the codebase.

**Comment by rzubek** [comment]
Added in https://github.com/rzubek/CSLisp/commit/93bd924ab9033d95dce34bbcbd0426f7f181522e
